-- Author: Prashant Mittal

DROP SCHEMA PUBLIC CASCADE;
CREATE SCHEMA PUBLIC;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE sessions (
    id SERIAL PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    time_start TIMESTAMP NOT NULL,
    time_end TIMESTAMP,
    duration INTERVAL
);

CREATE TABLE uploaded_documents (
    id SERIAL PRIMARY KEY,
    document_name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    project_name VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL
);

INSERT INTO USERS(username, password) VALUES('hi','hi');
